name: Automate Microsoft 365 App Manifest Release

on:
  push:
    paths:
      '**/*.json'
    branches-ignore:
      - main
      - live 

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create or Update PR to main with curl
        id: local_to_main_pr
        run: |
          PR_TITLE="Add / Update new schema files"
          PR_BODY="This PR adds or updates app and localization schema files to the repo's main branch"
          SOURCE_BRANCH="${{ github.ref }}"  # The source branch for the PR
          DESTINATION_BRANCH="main"         # The target branch for the PR
          
          # Construct the API URL
          REPO_URL="https://api.github.com/repos/${{ github.repository }}"
          
          # Check for existing pull requests
          EXISTING_PR_RESPONSE=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$REPO_URL/pulls?head=${{ github.repository }}:${SOURCE_BRANCH}&base=$DESTINATION_BRANCH")
      
          # Check if any PRs exist
          EXISTING_PR_NUMBER=$(echo "$EXISTING_PR_RESPONSE" | jq -r '.[0].number')
      
          if [ "$EXISTING_PR_NUMBER" != "null" ]; then
            echo "Found existing PR #$EXISTING_PR_NUMBER. Closing it..."
            
            # Close the existing PR
            curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d '{"state":"closed"}' \
              "$REPO_URL/pulls/$EXISTING_PR_NUMBER"
      
            echo "Closed existing PR #$EXISTING_PR_NUMBER."
          else
            echo "No existing PR found."
          fi
      
          # Create the pull request using curl
          RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"title\":\"$PR_TITLE\", \"body\":\"$PR_BODY\", \"head\":\"$SOURCE_BRANCH\", \"base\":\"$DESTINATION_BRANCH\"}" \
            "$REPO_URL/pulls")
          
          # Extract PR number from the response
          PR_NUMBER=$(echo "$RESPONSE" | jq -r '.number')
          
          if [ "$PR_NUMBER" == "null" ]; then
            echo "Failed to create pull request. Check the API response for details."
            exit 1
          fi
          
          echo "Created Pull Request Number: $PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Merge Pull Request
        run: |
          PR_NUMBER=${{ steps.local_to_main_pr.output.pr_number }}
          REPO_URL="https://api.github.com/repos/${{ github.repository }}"
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Merge the pull request using the GitHub API
          RESPONSE=$(curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "$REPO_URL/pulls/$PR_NUMBER/merge" \
            -d '{"commit_title":"Merging PR #'"$PR_NUMBER"'","commit_message":"Automatically merged by GitHub Actions.","merge_method":"merge"}')

          # Print the API response for debugging
          echo "Merge Response: $RESPONSE"

          # Check if the merge was successful
          MERGE_STATE=$(echo "$RESPONSE" | jq -r '.merged')
          if [ "$MERGE_STATE" != "true" ]; then
            echo "Failed to merge PR #$PR_NUMBER. Check the response for details."
            exit 1
          fi

          echo "Successfully merged PR #$PR_NUMBER."
          
      # Poll for PR status until it's closed
      - name: Monitor PR status
        run: |
          PR_NUMBER=${{ steps.local_to_main_pr.outputs.pr_number }}
          while [ "$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER | jq -r .state)" != "closed" ]; do
              echo "PR #$PR_NUMBER is not closed yet..."
              sleep 10
          done
          echo "PR local to main with number #$PR_NUMBER has been closed!"
